name: Setup Terraform Backend

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create S3 Bucket (if not exists)
        run: |
          BUCKET_NAME="${{ secrets.TF_BACKEND_BUCKET }}"
          REGION="${{ secrets.AWS_REGION }}"

          if aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
            echo "Bucket already exists."
          else
            echo "Creating bucket..."
            aws s3api create-bucket \
              --bucket $BUCKET_NAME \
              --region $REGION \
              --create-bucket-configuration LocationConstraint=$REGION
          fi

      - name: Create DynamoDB Table (if not exists)
        run: |
          TABLE_NAME="${{ secrets.TF_BACKEND_DDB_TABLE }}"

          if aws dynamodb describe-table --table-name $TABLE_NAME 2>/dev/null; then
            echo "DynamoDB table already exists."
          else
            echo "Creating DynamoDB table..."
            aws dynamodb create-table \
              --table-name $TABLE_NAME \
              --attribute-definitions AttributeName=LockID,AttributeType=S \
              --key-schema AttributeName=LockID,KeyType=HASH \
              --billing-mode PAY_PER_REQUEST
          fi
